name: Azure - CD

on:
  push: 
    branches: [ 'tjarbo/deploy' ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - run: npm install
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: 'upload'
          app_location: '/'
          app_build_command: 'npm run build'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN_PRD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          output_location: 'dist'

